// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let ReactIntl = require("react-intl");
let Stdlib_Option = require("@rescript/runtime/lib/js/Stdlib_Option.js");
let JsxRuntime = require("react/jsx-runtime");

let $$Intl = {};

let RawIntlProvider = {};

let IntlProvider = {};

let FormattedMessage = {};

let FormattedDate = {};

let FormattedDateParts = {};

let FormattedTime = {};

let FormattedTimeParts = {};

function ReactIntl$FormattedTimeWithSeparator(props) {
  let separator = props.separator;
  return JsxRuntime.jsx(ReactIntl.FormattedTimeParts, {
    value: props.value,
    timeZone: props.timeZone,
    hour12: props.hour12,
    month: props.month,
    hour: props.hour,
    minute: props.minute,
    second: props.second,
    children: formattedTimeParts => formattedTimeParts[0].value + Stdlib_Option.getOr(separator, formattedTimeParts[1].value) + formattedTimeParts[2].value
  });
}

let FormattedTimeWithSeparator = {
  make: ReactIntl$FormattedTimeWithSeparator
};

let FormattedRelativeTime = {};

let FormattedNumber = {};

let FormattedNumberParts = {};

let FormattedPlural = {};

let FormattedList = {};

let FormattedDisplayName = {};

exports.$$Intl = $$Intl;
exports.RawIntlProvider = RawIntlProvider;
exports.IntlProvider = IntlProvider;
exports.FormattedMessage = FormattedMessage;
exports.FormattedDate = FormattedDate;
exports.FormattedDateParts = FormattedDateParts;
exports.FormattedTime = FormattedTime;
exports.FormattedTimeParts = FormattedTimeParts;
exports.FormattedTimeWithSeparator = FormattedTimeWithSeparator;
exports.FormattedRelativeTime = FormattedRelativeTime;
exports.FormattedNumber = FormattedNumber;
exports.FormattedNumberParts = FormattedNumberParts;
exports.FormattedPlural = FormattedPlural;
exports.FormattedList = FormattedList;
exports.FormattedDisplayName = FormattedDisplayName;
/* react-intl Not a pure module */
