// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let ReactIntl = require("react-intl");
let JsxRuntime = require("react/jsx-runtime");

let Msg_hello = {
  id: "_8b1a9953",
  defaultMessage: "Hello"
};

let Msg_helloAgain = {
  id: "A",
  defaultMessage: "Hello again"
};

let Msg = {
  hello: Msg_hello,
  helloAgain: Msg_helloAgain
};

function Demo$Component1(props) {
  return JsxRuntime.jsx(ReactIntl.FormattedMessage, {
    id: "_0beb880a",
    defaultMessage: "Some default message"
  });
}

let Component1 = {
  make: Demo$Component1
};

function Demo$Component2(props) {
  return JsxRuntime.jsx(ReactIntl.FormattedMessage, {
    id: "B",
    defaultMessage: "Some default message with id"
  });
}

let Component2 = {
  make: Demo$Component2
};

function Demo$Component3(props) {
  return JsxRuntime.jsx(ReactIntl.FormattedMessage, {
    id: "C",
    defaultMessage: "Some default message with id and values {foo}",
    values: {
      foo: JsxRuntime.jsx(ReactIntl.FormattedMessage, {
        id: "D",
        defaultMessage: "Somme wrapped message"
      })
    }
  });
}

let Component3 = {
  make: Demo$Component3
};

exports.Msg = Msg;
exports.Component1 = Component1;
exports.Component2 = Component2;
exports.Component3 = Component3;
/* react-intl Not a pure module */
